#given a DNA sequence, count the number of each nucleotide

s = "GAGCTATGACTCTCCATCTTGCCGGGGGGGCCATACTATTGCCCCCAGGTCGATTACAGCGCCTGGATCGAATGTCCGTCCCGGATCTGAGATCGTTCAAGTTAGCCGTATAAAGAGTTCGCTACAAAAAATAAGAATATAATGCGTGTTCACCAATGCGCAAAATGAGAATAGTTCCGAATCGGAGAGTCGTCGTATGATATTACATAGGAATACGCGATCACGCTCGAATTCTTAAAAGTCTGGTATTCTTGCCTGCGCGGCTCCCACATACCAAGCTTAAGGTTCGTAAAGGGCGCAGAGTTTATGTTCGCTTTAAGTATGGGTGAAGATGATTTTATCTTTGTGAATCCCTACCGATTCACATTCATCCTAATGTAACAATAGGATCCTCCAGGGGTGGTAACAGGTGCTAAAGCGCTACTTTTGCTTATCCGAGTTGGTGACGCCGCTGGGTACAACCTCGGTCCGGCCACCCTGATTCTTCACTGGGGTGCGGTTGCAGGCCGAGAGCCTCTGGAAGTTGGACGGACAGTTTCGCTTACTATTTCACCGCAGGGTAACGCACTGGCCACATGACAATCTGCAGGTTCATGTCATTAATAGTCAGAAATAACGCGTGACCATACAAGCGCTGCTGGTCGCCGCTCATAGCGCATATACCTACTATACCTTTGTCTTCGTCGGTGGTGGGCAAGTGGACATGCGACTAACGAGATACTTATAGTAGCCGGGCTAATATACGAGAGGCACCATTTTTAACCACGAAACAAGTTGCATCTGTAGAGCTGCGTCCAGCTTCAAGTACATTCACAGGCGAATCTAAACAGCTTGGGAAATCAATAGCGGAGTGAAGGAGGCCGAGGAGGTGAGTCATCCTACGCCCTCAAGGACACATATATTTCTTAGTACGGAAAGTTCTGAAGTCCCTCTCCGAATAATCGCAGTGGGAGCCCGCGGCTG"

l = float(len(s)) #length of sequence

g = float(s.count('G'))
c = float(s.count('C'))
a = float(s.count('A'))
t = float(s.count('T'))

print "Sequence length:", l
print "G: %s A: %s C: %s T: %s" % (g, a, c, t)


print "In percentages:"

gp = (100 * g / l)
ap = (100 * a / l)
cp = (100 * c / l)
tp = (100 * t / l)

#print gp + ap + cp + tp #should be 100.0

print "G: ", gp, "% ", "A: ", ap, "% ", "C: ", cp, "% ", "T: ", tp, "%"


