#Given two strings s and t, t is a substring of s if t is contained as a contiguous 
#collection of symbols in s (as a result, t must be no longer than s).
#Find all positions of t in s.

#DNA sequence
s = "CAAATGCTTAGAATGCTTAATGCTTATTATGCTTAATGCTTATATGCTTAACATGCTTAGCCGATGCTTAATGCTTACATGCTTAATGCTTAATGCTTACAAGGAAATGCTTATATATGCTTAATGCTTAACATGCTTAATGCTTATTATGCTTATGTTGCAGCTTATGCTTAGAAATATATGCTTAAATGCTTAATGCTTACATGCTTAGCCTAGTTCACATGCTTAATATGCTTATATGCTTACGATGCTTACGCATATGCTTAGGCACATGCTTAGAATGCTTATAGATGCTTAATGCTTAACAACTATGCTTACTATGCTTAATGCTTAATGCTTATAAGTTGTTATATCAGAAGCTTATGCTTATGATGCTTATTATGCTTATATGCTTAGATGCTTATATGCTTAAACCATGCTTAATGCTTAGCTATGCTTAATGCTTAACAACTATGCTTAATGCTTAGTCCGATGCTTAAATGCTTAACATGCTTATATGCTTAATGCTTATAGCCTATGCTTACATCCAATGCTTAGAACAATGCTTATATGCTTAATGCTTACTTCTTACCATGCTTAATGCTTAGCATGCTTACATGCTTACGATGCTTAGGTATGCTTAAAAACTGATGATGCTTACGCGGTGCATGCTTACATGGACTAATGCTTAATGCTTACTATGCTTAATGCTTAAGATATATGCTTATATGCTTACCATGCTTAACATGCTTATATGCTTAGGCGCTCGATGCTTACCTGCGCCCCTGCAAATGCTTAATGCTTAAATAGTATGCTTAATGCTTAATGCTTAGATATGCTTAGAGAATGCTTATATGCTTACATGCTTAATGCTTAGGTATGCTTACTTAATGCTTATAGTATGCTTAATGCTTAGAATGCTTAATGCTTAATGCTTATTAAATGCTTAATGCTTAATGCTTA"

#Motif
t = "ATGCTTAAT"

#if s from index i to i + the length of t is the same as t, print index i + 1 (ordered)
for i in range(len(s)): 
	if s[i:i+len(t)] == t: 
		print i + 1,
		
#prints 13 29 64 79 86 117 133 189 222 291 320 327 416 433 453 497 550 573 664 680 771 791 798 842 881 897 904 922 929